### ISSUE TITLE
workshop textures problems in 44.09 LNP

### ISSUE THREAD

**Issue by Eddyskingdom** [DFgraphics/Phoebus#15]
i have seen you have tried to fix it but its back again if you build the work shops in virsion 44.09 the workshop wil not have any tabels  or phoebus texturs and yes i have TWBT ON
virsion 6.41

**Comment by Eddyskingdom** [comment]
![image](https://user-images.githubusercontent.com/25956554/39538704-eee44cec-4e3d-11e8-950e-84db5d6c20b9.png)

**Comment by Eddyskingdom** [comment]
ok let talk here

**Comment by Eddyskingdom** [comment]
also yes not all the workshops have tabels but some have bookcases and some have other thing like the look workshop 
but there are are also some texturs missing from bins bins look like U/D stairs
farmplots look like dirt roads

**Comment by Eddyskingdom** [comment]
@jecowa

**Comment by jecowa** [comment]
Sorry about that. It sounds like you don't have the TWBT components installed. The TWBT components were removed to add support for cool new TWBT transparency features without degrading the pack for non-TWBT users.

Here's the instructions to install the TWBT content:

1. Copy the contents of the /data/twbt_art/ folder to the /data/art/.
2. Copy the contents of the /data/twbt_init/ folder to the /data/init/.
3. Copy the contents of the /raw/twbt_graphics/ folder to the /raw/graphics/.
4. Copy the contents of the /raw/twbt_objects/ folder to the /raw/objects/.
5. Copy the "onLoad_gfx_Phoebus.init" file into the /raw/ folder.

**Comment by Eddyskingdom** [comment]
thank you for responding u will try to do dis and see if it works

**Comment by Eddyskingdom** [comment]
@jecowa thank you so much my game looks good again but one more thing why duze dis happen?
