### ISSUE TITLE
Random text missing sometime?

### ISSUE THREAD

**Issue by timo103** [DFgraphics/Phoebus#17]
I'm having random bits of text disappear from view.

Sometimes it's dwarf names/careers when I hover over them, sometimes it's other random bits of text.

https://i.imgur.com/JoXKbTe.png

https://i.imgur.com/LSWdVIZ.png

Two simple examples, it just blacks out the letters sometimes.

**Comment by jecowa** [comment]
Try pressing F10. If that doesn't work, try opening the unit.txt file and changing the value for "TRUETYPE" from "YES" to "NO".

**Comment by jecowa** [comment]
Try pressing F10. If that doesn't work, try disabling TrueType. (This can
be done by opening /data/init/init.txt and changing the value for "TRUETYPE" from "YES" to "NO".)

**Comment by claireanlage** [comment]
[known True Type bug unrelated to Phoebus.](http://www.bay12games.com/dwarves/mantisbt/view.php?id=5097)
