### ISSUE TITLE
File tokens in graphics_jecowa_messenger.txt need to be capitalised for linux.

### ISSUE THREAD

**Issue by NothingClever** [DFgraphics/Phoebus#18]
In the file graphics_jecowa_messenger.txt the file tokens use 
[FILE:jecowa/\*] 
when on linux the jecowa folder is capitalised as Jecowa. So the tokens need to be 
[FILE:Jecowa/\*]
It affects all three messengers in version 44.11

**Comment by jecowa** [comment]
Thank you for the notice. I'm switching it to lower case to try to prevent this from happening again. I think this isn't the first time I've forgotten to capitalize.
