### ISSUE TITLE
Can't tell what quality an item is

### ISSUE THREAD

**Issue by Shardj** [DFgraphics/Phoebus#21]
This set doesn't seem to follow the normal characters for quality, there's one which is just a box

\-

\+

\*

≡

☼

No idea what quality the bottom mechanism is in this screenshot https://imgur.com/fVtI6Wj

**Comment by jecowa** [comment]
Sorry, there's a limited number of tiles to work with. The TWBT version of this tileset has access to a lot more tiles to keep the text including the quality markers looking like they are supposed to.

If you want a more ASCII style experience with more familiar quality markers, but don't want to use TWBT, you can try changing your Graphics_Font from "Phoebus_16x16.png" to "Phoebus_16x16_text.png" to see if that works okay for you.

Or if you want to keep using the same tilesheet but want a guide, here it is:

![phoebus quality marker guide](https://user-images.githubusercontent.com/8553687/77838354-d4c4dc80-7138-11ea-9062-e21b281d1a35.png)

**Comment by Shardj** [comment]
Thanks
