### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by abbradar** [DFgraphics/Phoebus#5]
Hi,
I help to bring Phoebus tileset as a package to NixOS Linux distribution. To distribute a package we need to know a license under which it's published. I wasn't able to find any information about it either on forums or in the repository -- can you please clarify this?

**Comment by sv-esk** [comment]
> On that subject, yes you are free to add things to the graphic pack, or make your own version of the graphic pack. Most of the art in the pack has been, borrowed, from the community, and I've created to pack for the benefit of the community. Feel free to use or improve it as you wish.

1)http://www.bay12forums.com/smf/index.php?topic=137096.msg6670711#msg6670711
2)http://www.bay12forums.com/smf/index.php?topic=137096.msg6674819#msg6674819

I guess, that means cc-by license or so, if this quote cant be considered as license info itself

**Comment by abbradar** [comment]
Thanks! I think I'll specify the license as "custom free", it seems the most close choice.
